env:
  matrix:
    - PYVER="2.7"
    - PYVER="3.5"
    - PYVER="3.6"

sudo: false

os:
  - linux
  - osx

before_install:
  - |
    if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then 
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -O miniconda.sh;
      mkdir $HOME/.matplotlib;
      echo "backend: TkAgg" >> $HOME/.matplotlib/matplotlibrc;
    fi
  - |
    if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then 
      sudo apt-get update;
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a

install:
  - conda create --yes -n pylbm_env python=$PYVER nose numpy mpi4py h5py
  - source activate pylbm_env
  - python --version
  - python setup.py install
  - which nosetests

script: nosetests
