sudo:
  false

language: python

python:
    - "2.7"
    - "3.3"
    - "3.4"
    - "3.5"

addons:
  apt:
    packages:
      - gfortran
      - libopenmpi-dev
      - openmpi-bin
      - openmpi-common 
      - liblapack-dev
      - libatlas-base-dev
      - libatlas-dev
      - mercurial

install:
    - travis_wait pip install scipy
    - travis_wait pip install -r requirements.txt
    - travis_wait pip install .

script: nosetests
