name: pylbm
dependencies:
  - python=2.7
  - mercurial
  - numpy>1.9.*
  - mpi4py
  - sympy
  - Cython
  - matplotlib
  - future
  - ipython
  - notebook
  - nbconvert
  - h5py
  - numpydoc
  - pip
  - pip:
     - colorlog
     - hg+https://bitbucket.org/pauloh/pyevtk